version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm run co:login
      - npm install
  build:
    commands:
      - npm publish --unsafe-perm