export type Policy = {
  agencyCode: string
  agencyName: string
  agentEmail: string
  agentName: string
  agentPhone: string
  allowPayment: string
  annualPremium: string
  assetId: string
  assetType: string
  balanceDueCurrent: string
  balanceDueFuture: string
  bankName: string
  bankNumber: string
  billAmount: string
  billDate: string
  billedName: string
  billingAddressLine1: string
  billingAddressLine2: string
  billingCityStateZip: string
  cancelledDate: string
  cancelReasonCode: string
  cancelReasonText: string
  companyCode: string
  companyName: string
  coverageA: string
  coverageB: string
  coverageC: string
  coverageD: string
  creditCardFee: string
  debitAmount: string
  debitDate: string
  effectiveDate: string
  email: string
  emergencyServicesOptIn: boolean
  expirationDate: string
  inForce: boolean
  lastPaymentAmount: string
  lastPaymentDate: string
  lastUpdated: string
  lateFee: string
  latitude: string
  locationAddressLine1: string
  locationAddressLine2: string
  locationCity: string
  locationCounty: string
  locationState: string
  locationZip: string
  locationZipFour: string
  longitude: string
  mailingAddressLine1: string
  mailingAddressLine2: string
  mailingCity: string
  mailingCounty: string
  mailingState: string
  mailingZip: string
  mailingZipFour: string
  nextPaymentAmount: string
  nextPaymentDate: string
  nsFee: string
  originalPremium: string
  pastDueAmount: string
  paymentPasscode: string
  paymentPlanType: string
  paymentStatus: string
  payoffAmount: string
  policyHash: string
  policyNumber: string
  preferedContactMethod: string
  primaryEmail: string
  primaryFirstName: string
  primaryLastName: string
  primaryLastNameLower: string
  primaryPhone: string
  producerCode: string
  productNumber: string
  productType: string
  pushNotificationsOptIn: string
  reinstateFee: string
  salesEmail: string
  salesName: string
  secondaryFirstName: string
  secondaryLastName: string
  serviceArea: string
  windCoverage: boolean
}